# Numpy Practice 

In [1]:
import numpy as np

## Declaring arrays in numpy

In [3]:
## Creating Arrays and Matrices in numpy
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
print(type(x))
## The type is 'ndarray'

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## numpy.shape attribute -> (row, col)

In [5]:
## The ndarray.shape attribute ->  (row,cols)
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([
    [1,2,3],
    [2,3,4]
])
z = np.array([
    [1],
    [2],
    [3]
])

print(x.shape)
print(y.shape)
print(z.shape)

(9,)
(2, 3)
(3, 1)


## Indexing and Slicing in numpy

In [10]:
## Indexing and slicing
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

print(x[1])
print(x[1][1])
print(x[0:2,0:2])  ## x[start_row_index : end_row_index + 1, start_col_index : end_col_index + 1]
print(x[:,:])
print(x[0:,1])
print(x[1:,1:])

[2 3 4]
3
[[1 2]
 [2 3]]
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[2 3 4 5]
[[3 4]
 [4 5]
 [5 6]]


## numpy.dtype attribute 

In [17]:
x = np.array([1,2,3,4,5])
print(x.dtype)
x = np.array([1,2,3,4,5],dtype=float)
print(x.dtype)
print(x)
x = np.array([1,2,3,4,5],dtype=complex)
print(x.dtype)
print(x)
x = np.array([1,2,3,4,5],dtype=np.int64)
print(x.dtype)
x = np.array([1,2,3,4,5],dtype=np.int16)
print(x.dtype)

int32
float64
[1. 2. 3. 4. 5.]
complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
int64
int16


## Some other attributes

In [20]:
x = np.array([[1,2,3,4,5],[2,3,4,5,6]],dtype=np.int16)
print(x.size) # rows*cols -> 2*5
print(x.dtype)
print(x.ndim) # Number of axes of the array

10
int16
2


## Creating array of zeros, ones and custom array

In [22]:
x = np.zeros((3,3))
print(x)
x = np.zeros((3,4),dtype=np.int16)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
x = np.full((2,3),5,dtype=np.int32)
print(x)
x = np.full((4,3),5,dtype=float)
print(x)

[[5 5 5]
 [5 5 5]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


## Matrix Operations

In [48]:
x = np.array([
    [1,2],
    [2,3]
])
y = np.array([
    [4,5],
    [5,6]
])

# Element wise operations
print(x+y)
print(np.add(x,y))
#########################
print(x-y)
print(np.subtract(x,y))
#########################
print(x*y)
print(np.multiply(x,y))
#########################
print(x/y)
print(np.divide(x,y))
#########################
print(np.sqrt(x))
#########################
print(x**2)
#########################
print(x**2 + 3*y)

[[5 7]
 [7 9]]
[[5 7]
 [7 9]]
[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [10 18]]
[[ 4 10]
 [10 18]]
[[0.25 0.4 ]
 [0.4  0.5 ]]
[[0.25 0.4 ]
 [0.4  0.5 ]]
[[1.         1.41421356]
 [1.41421356 1.73205081]]
[[1 4]
 [4 9]]
[[13 19]
 [19 27]]


In [34]:
# Matrix multiplication
print(x.dot(y))
print(np.dot(x,y))


# dot of vectors
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

print(a.dot(b))
print(np.dot(a,b))

[[14 17]
 [23 28]]
[[14 17]
 [23 28]]
40
40


## Some other mathematical operations and functions

In [42]:
x = np.array([1,2,3,4])
print(np.sum(x))

x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

print(np.sum(x))
print(np.sum(x,axis=0)) ## along the column sum
print(np.sum(x,axis=1)) ## along the row sum

10
42
[10 14 18]
[ 6  9 12 15]


In [44]:
## np.arange(start_val,end_val+1,increment)
x = np.arange(10)
print(x)
x = np.arange(10,20)
print(x)
x = np.arange(10,20,2)
print(x)
x = np.arange(10,20,0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


In [49]:
# Transpose of a matrix

x = np.array([
    [1,1,3],
    [2,3,4],
    [1,2,5]
])

print(x)
y = x.T
print(y)

[[1 1 3]
 [2 3 4]
 [1 2 5]]
[[1 2 1]
 [1 3 2]
 [3 4 5]]


In [50]:
## Reshaping a numpy array
x = np.array([
    [1,4,9,16],
    [25,36,49,64]
])

print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


## ndarray.reshape

In [55]:
x = x.reshape((4,2))
print(x)
print()
x = x.reshape((8,1))
print(x)
print()
x = x.reshape((1,8))
print(x)
print()
x = x.reshape(8)
print(x)
print()
x = x.reshape((2,-1))
print(x)
print()
x = x.reshape((4,-1)) # We want to have 4 rows but we are not sure how to calculate the columns then we specify -1
print(x)
print()
x = x.reshape((-1,2))
print(x)
print()
x = x.reshape((-1,4))
print(x)
print()


[[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]

[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]
 [36]
 [49]
 [64]]

[[ 1  4  9 16 25 36 49 64]]

[ 1  4  9 16 25 36 49 64]

[[ 1  4  9 16]
 [25 36 49 64]]

[[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]

[[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]

[[ 1  4  9 16]
 [25 36 49 64]]



In [8]:
## ndarray.linspace
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [9]:
print(np.linspace(10,20,num=20))

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


## Stacking of arrays

In [3]:
## Stacking of arrays
a = np.array([[1,2,3,4],[2,3,4,5]])
b = np.array([[2,3,4,5],[3,4,5,6]])

b = b**2
print(a)
print(b)

[[1 2 3 4]
 [2 3 4 5]]
[[ 4  9 16 25]
 [ 9 16 25 36]]


In [4]:
np.stack((a,b),axis=0)

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5]],

       [[ 4,  9, 16, 25],
        [ 9, 16, 25, 36]]])

In [5]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3,  4],
        [ 4,  9, 16, 25]],

       [[ 2,  3,  4,  5],
        [ 9, 16, 25, 36]]])

In [6]:
np.vstack((a,b)) ## only works when the number of columns are same

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 4,  9, 16, 25],
       [ 9, 16, 25, 36]])

In [7]:
np.hstack((a,b)) ## only works when the rows are same

array([[ 1,  2,  3,  4,  4,  9, 16, 25],
       [ 2,  3,  4,  5,  9, 16, 25, 36]])

In [8]:
a = np.array([1,2,3,4])
b = np.array([1,2,2,3])
print(a,b,sep='\n')

[1 2 3 4]
[1 2 2 3]


In [9]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [1, 2, 2, 3]])

In [10]:
np.stack((a,b),axis=1)

array([[1, 1],
       [2, 2],
       [3, 2],
       [4, 3]])

In [65]:
### Stack is not clear

## Random Module

In [66]:
# Random Matrix
randomMatrix = np.random.random((2,3)) ## np.random.random(matrix size) -> random values from uniform normal distribution
print(randomMatrix)

[[0.72318185 0.0611261  0.88362907]
 [0.25071442 0.19611818 0.08965343]]


In [68]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [69]:
np.random.shuffle(a)
print(a)

[ 5 10  9 11  8 12  7 14  6 13]


In [72]:
a = np.random.rand(2,3)
# Returns values from Uniform Distribution
print(a)
print()
# Returns values from Standard Normal Distribution
a = np.random.randn(2,3)
print(a)

# randint(low, high=None, size=None, dtype='l')
a = np.random.randint(5,10,3)
print(a)

[[0.65660795 0.01317373 0.80706514]
 [0.05162718 0.88450876 0.86930195]]

[[-1.2770393   0.53404701  0.51001961]
 [-0.126736   -0.08018814  0.36549922]]
[8 7 8]


In [73]:
# Randomly pick one element from an array
# choice(a, size=None, replace=True, p=None) -> Generates a random sample from a given 1-D array
element = np.random.choice([1,2,3,4,5,6,7,8,9])
print(element)

3


In [74]:
np.random.choice? ## Prints the docstring

In [75]:
## seed() value is important

## Statistical Operations

In [3]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# axis = 0 -> works along columns
# axis = 1 -> works along rows

print(np.min(a))
print(np.max(a))

print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
8
[1 2 3 4]
[1 5]


In [5]:
# Mean function

b = np.array([1,2,3,4,5])
m = sum(b)/5

print(m)
print(np.mean(b))

3.0
3.0


In [6]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[3. 4. 5. 6.]
[2.5 6.5]


In [7]:
print(np.mean(a))

4.5


In [8]:
print(b)
print(np.median(b))

[1 2 3 4 5]
3.0


In [9]:
# Mean vs Average(is weighted)

arr = np.array([1,2,5,4,6,8,9])
wts = np.array([2,3,1,3,4,5,6])

print(np.average(arr,weights=wts))

5.958333333333333


In [10]:
# Standard Deviation
print(arr)
u = np.mean(arr)
std = np.sqrt(np.mean(abs(arr-u)**2))
print(std)

[1 2 5 4 6 8 9]
2.7255405754769875


In [11]:
print(np.std(arr))

2.7255405754769875


In [12]:
# Variance 
print(std**2)

print(np.var(arr))

7.428571428571428
7.428571428571429


## Iterating over arrays

In [2]:
import numpy as np
x = np.array([
    [1,2,3,4],
    [2,3,4,5]
])

for i in x:
    for j in i:
        print(j,end=" ")
    print()
    
row = x.shape[0]
col = x.shape[1]
print(row)

for i in range(row):
    for j in range(col):
        print(x[i][j],end=" ")
    print()


1 2 3 4 
2 3 4 5 
2
1 2 3 4 
2 3 4 5 
